### ISSUE TITLE
Crawlers Disallowed by Default

### ISSUE THREAD

**Issue by ramiyahya** [linuxserver/docker-letsencrypt#105]
This is more of a 'note' than it is an issue. The default [nginx configuration](docker-letsencrypt/root/defaults/nginx.conf) adds `X-Robots-Tag none;` header. While this is great when you're testing, people might overlook to remove it once they've gone live. It took some research to realise that `X-Robots-Tag none;` is equivalent to `X-Robots-Tag noindex;`.[ref](https://developers.google.com/search/reference/robots_meta_tag#using-the-x-robots-tag-http-header) 

It might be worthwhile adding a note/reminder in the defaults to edit/remove `X-Robots-Tag` as required.

**Comment by aptalca** [comment]
The original purpose of this image was to provide a secure reverse proxy for other docker containers' guis. For that, bot indexing was undesirable and that's why it's there. Plus, nginx.conf is user customizable so you can easily remove that.

There is a big rewrite coming up, which will make that directive and others optional and off by default.
