### ISSUE TITLE
Dynamic DNS

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-letsencrypt#138]
My server is behind a DS-Lite (Dual Stack) connection. I can't use IPv4, only IPv6. The IPv6 is fairly static but can change a couple of times in a year. I found some docker containers that will auto renew my DNS record at cloudflare but I guess this is not working since I also would need to update the SSL certificate(s).
Do you might have an idea how I could solve my current situation? Maybe a feature request for dynamic DNS? The implementation is (for cloudflare) fairly simple.

**Comment by aptalca** [comment]
? I don't think I follow you. Specifically, I don't understand what you mean by "I found some docker containers that will auto renew my DNS record at cloudflare but I guess this is not working since I also would need to update the SSL certificate(s)." why would you need to update the ssl cert when your ip changes? The cert is tied to domain name, not ip. 

You can use a different docker (like ddclient) to update the cloudflare record. Or even some routers do that. That is only so you can connect to the right ip. 

With this image, you can validate for letsencrypt cert via dns on cloudflare, so you don't have to worry about ipv4 or ipv6

**Comment by jwillmer** [comment]
o.k. perfect then I was misinformed.
