### ISSUE TITLE
HTTPS redirect disabled by default

### ISSUE THREAD

**Issue by insuusvenerati** [linuxserver/docker-letsencrypt#184]
Uncomment HTTPS redirect so it's enabled by default. Not sure why anyone would want an https only server block on nginx. This forces anyone visiting the site to type https or get an error that they cannot connect.

**Comment by LBegnaud** [comment]
I vote to remove that section and put it as an example config that isn't loaded by default. We currently have a deployment scheme that uses this project and a custom port 80 config.

to your point about port 80 giving an error, one already has to configure conf files for whatever services you're proxying, moving one example config to redirect to https should be trivial.

**Comment by nemchik** [comment]
I would vote against this as well. I'm not keen on it being in a separate config outside of `default` where it is right now. I think it should stay right where it is (commented).

**Comment by insuusvenerati** [comment]
Honestly I can't really think of a valid solution other than it being the way it is. I, for some reason, thought it was more difficult to access. Just bind mounting the whole config directory worked fine though.

**Comment by LBegnaud** [comment]
yea @insuusvenerati that's part of the suggested setup, to use `-v <localPath>:/config`. AFAIK default.conf won't be overwritten on version updates, too.

**Comment by nemchik** [comment]
Given a little more thought, if this container is run in bridge mode and that section is enabled (uncommented) by default, users can simply not map port 80 to this container if they have other needs. Other network modes would be a different story.

Thoughts?

**Comment by LBegnaud** [comment]
isn't port 80 needed for LE validation?

**Comment by nemchik** [comment]
For http validation, yes. Not for dns.

**Comment by aptalca** [comment]
Port 80 mapping is required for http validation.

The reason it's not listening on 80 by default is so that the users don't accidentally host things insecurely. They are supposed to modify the confs anyway during inital setup, they can easily enable if they choose to. Instructions are right there.

Also, if one enables hsts and registers with google for preloading, there is no need for port 80 listening. The browsers automatically load the https version (settings for that are also in the confs)

We provide the tools, the users can configure however they like
