### ISSUE TITLE
Add cpanel as dns authenticator option

### ISSUE THREAD

**Issue by mrrsm** [linuxserver/docker-letsencrypt#246]
I would like to be able to use dns authentication to get certificates however my domain is configured to use cpanel for its dns.

From what I have seen the easiest way to do this is via certbot hooks and a script that creates/deletes the dns record.

I was able to cobble something together using [this script](https://github.com/letsdebug/certbot-cpanel-dns-auth-hook) with some slight modifications so it ran properly from the 50-init script so I know it can be done. I'm not sure if this is the best way to implement it though.

**Comment by aptalca** [comment]
Currently we use the official certbot plugins for dns validation: https://github.com/certbot/certbot

The only custom dns solution we implemented is for duckdns and that's because we really wanted to provide a completely free option for wildcard certs (no need to buy a domain).

We'd rather not implement any other custom solutions because the cert generation algorithm is already getting too complicated and tricky to maintain.

**Comment by mrrsm** [comment]
Before I open a new issue would adding a custom field and allowing a user to directly set $PREFCHAL rather then use only the ones that are built in be reasonable?  This allows an end user to do something different and should take next to no maintenance.

**Comment by aptalca** [comment]
Oh no, that would be a support nightmare.
