### ISSUE TITLE
Add a default http 200 return code on / as healthcheck for K8s Ingress

### ISSUE THREAD

**Issue by zxpectre** [linuxserver/docker-letsencrypt#257]
Hi, I'm having some trouble with GKE Ingress, i guess your awesome image is not passing it's dumb health check. Could you add a default http 200 return code on path / as health check as soon as the container is up? An env var to enable this?

If as soon as it starts, it serves web root on port 80, I have something wrong on my infrastructure! Hope not!

**Comment by aptalca** [comment]
I know nothing about k8s or is health check but if all you want is to serve a 200 on /, you can do it through the site config

https://serverfault.com/questions/196929/reply-with-200-from-nginx-config-without-serving-a-file

**Comment by zxpectre** [comment]
Thanks @aptalca, thats the right way to do it  but that didn't work for me. I think is a chicken-egg problem, _docker-letsencrypt_ fails to deliver the healthcheck in time and ingress don't route requests to _docker-letsencrypt_ so it fails to pass the http validation, it hits Error 502 Bad Gateway

I'll resume this later ,as for now I'm in a hurry.

**Comment by aptalca** [comment]
You need to rethink your workflow because nginx isn't even up until validation is completed. Certbot puts up its own webserver during that if you're using http validation. So if ingress doesn't route anything until the 200, it won't work.

You can however do dns validation, that doesn't require an incoming connection to the container during validation and once validation is done, nginx will go up and will serve the 200

**Comment by zxpectre** [comment]
You are right, that seems to be happening. 
Not more time. Dns validation will be. Thanks.
