### ISSUE TITLE
reverse proxy to guacamole gives main welcome page

### ISSUE THREAD

**Issue by dendenyc** [linuxserver/docker-letsencrypt#277]
configured guacamole subdomain by removing .sample and adding a dns CNAME guacamole = real.hostname.com however when go to https://real.hostname.com I get the main "Welcome to our server" page. 

Guacamole is running on http://real.hostname.com:8080

**Comment by nemchik** [comment]
Subdomain config would get you https://guacamole.real.hostname.com/ or something similar out of the box unless you changed the contents of the conf

**Comment by dendenyc** [comment]
I see what you're saying and I think I didnt explain myself correctly.

The external domain that letsencrypt is securing is https://real.domain.com the setup for this works fine, https works and it brings up the main welcome page.  The problem I'm having is getting reverse proxy to forward those requests to an internal subdomain called http://guacamole.real.domain.com:8080.

**Comment by nemchik** [comment]
Are you running guacamole and letsencrypt both in docker on the same host and attached to the same user defined bridge network?

**Comment by dendenyc** [comment]
Yes, both are running on docker on the same host, I'll double check the network bridge but I haven't configured anything specifically for that so I'd assume they're on the same bridge.

**Comment by aptalca** [comment]
@dendenyc I think you are confused.

With the reverse proxy, you would access https://guacamole.real.domain.com and letsencrypt would connect to guacamole through the docker dns. You don't use the 8080 port because that is just a direct forwarded port to guacamole and not what you want (not proxied). 

You also need to make sure the containers are on the same `user defined bridge` network

**Comment by dendenyc** [comment]
@aptalca its very likely that I am confused.

Would I then need to configure letsencrypt to secure "guacamole.real.domain.com"? I thought the whole point to reverse proxy was to not have to expose stuff on your internal network to the internet?

From a security perspective I would have preferred not to expose "guacamole.real.domain.com" DNS to the internet, letsencrypt is already pointing to https://real.domain.com is there a way to reverse proxy that to the internal host guacamole.real.domain.com or am I missing something?

**Comment by aptalca** [comment]
?? The whole point of reverse proxy is to expose stuff on your internal network to the internet "in a secure manner" with an ssl cert.

Currently you are port forwarding directly to guacamole and it is not secure.

Tell us what you are trying to accomplish and we'll help you.

The reverse proxy config we provide for guacamole already sets up letsencrypt for guacamole to be accessible at the https://guacamole.yourdomain.com address with an ssl cert, encrypted connection that you can also protect with http auth and fail2ban.

If you are worried about your url being listed on dns servers, that's how dns servers work. They are like phonebooks, that list and translate urls to IP addresses.

If you really don't want anyone to ~know~ easily discover you have guacamole running on your server you need to either reverse proxy via the subfolder method (we don't provide a working one for guacamole) or you can get a wildcard cert, so your dns only has a cname for `*` instead of each service spelled out

**Comment by dendenyc** [comment]
ok, I think that's the key here I need to setup the ssl cert on https://guacamole.yourdomain.com as opposed to how I have it now where ssl is setup on https://your.domain.com and expecting it to forward to https://guacamole.your.domain.com.

**Comment by aptalca** [comment]
add guacamole to subdomains in your docker run/create or compose yml

**Comment by dendenyc** [comment]
Im happy to report this now works and the error was due to an internal DNS issue. Adding the user defined bridge in docker was key to discovering the DNS problems. Thanks to all.
