### ISSUE TITLE
Container doesn't generate .p12 files

### ISSUE THREAD

**Issue by dancmeyers** [linuxserver/docker-letsencrypt#292]
I'm trying to use the letsencrypt container to do two things:

1) Forward requests to my Plex instance with a reverse proxy in front of said Plex instance so that requests to my.domain.com/plex go to my Plex instance
2) Provide the generated letsencrypt certificate to Plex so that even the exposed 32400 port for remote access is SSL secured (I actually have the standard route of subfolders secured using SSL client certificates, so I'm not expecting Plex remote access to work through that on port 443)

1 works fine. I can view my Plex instance. But for 2 I need a p12 format SSL certificate. I can generate one easily enough using `openssl`, but I'd need to redo that every time the letsencrypt container regenerated my certificate. It'd be ace if the container would do that for me. I figured either the passphrase to use could be specified as an argument/env var, or it could be generated with an empty passphrase.

I did wonder if the pfx file could be used for this, but it seems to have a passphrase on at least the key part with no indication I can find of what that passphrase _is_.

I'm happy to try and work out the guts of the container and have a bash at doing it myself and submitting a pull request, but this sounded like the sort of thing I'd spend ages understanding first, whereas someone who knows how the container is built already could do it in half an hour or less.

**Comment by aptalca** [comment]
There is no passphrase on the pfx it generates. It may be treated as a blank passphrase, not sure.

For item number 2, you shouldn't need to provide your own cert to plex because Plex already uses its own trusted cert for its built in remote access.

When you access Plex through your own domain it is the letsencrypt cert that is used since all communication flows through the letsencrypt container.

Also, if you follow all the instructions in the Plex proxy conf we provide, you can go ahead and turn off Plex's built in remote access, get rid of the port forwarding for 32400 and let every Plex client (including web and mobile) use your reverse proxy so everything will use your letsencrypt cert.
