### ISSUE TITLE
openssl handshake fail

### ISSUE THREAD

**Issue by alexpong0630** [linuxserver/docker-letsencrypt#312]
Hello, I created the container on armhf debian 9, but got this error.

`
requests.exceptions.SSLError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
`

Since the container host is armhf debian 9 with openssl 1.1.0j (latest version in apt)
I tried to use openssl connect letsencrypt api endpoint and it can recognize the the chiper and create session successfully
```
openssl s_client -connect acme-v02.api.letsencrypt.org:443
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384

```

Then, I bash in the docker(openssl 1.1.1b) and execute same command. It cannot recognize the chiper
```
root@orangepiplus2e:~# docker exec -it letsencrypt bash
root@orangepiplus2e:/$ openssl s_client -connect acme-v02.api.letsencrypt.org:443
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 330 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

I am new in linux system. please forgive me asking stupid questions.
Would it be possible the openssl in the docker is not compatible with my armhf debian 9 machine?  and how to fix it.  Thanks.

**Comment by nemchik** [comment]
The version of OpenSSL you have on the Debian system should not really matter or conflict with what is run inside the container. The version inside the container is tested and working for the purpose the container serves.

The error you're getting looks like a rate limit, possibly due to too many failed attempts or too many attempts to reissue the same cert. If you have previously had the container working then you might just need to add/subtract a subdomain if possible which will get the cert to regenerate. If you have never had this setup working before my guess would be this is a port forwarding issue. You should ensure that you have both ports 80 and 443 forwarded on your router to your Debian system.

**Comment by alexpong0630** [comment]
Hello nemchik, I never had this setup working before and I think it passed the http challenge.
Then, it seems trying to communticate with  letsencrypt api endpoint. At the end the openssl handshake fail.
```
2048 bit DH parameters present
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d xxxxxxxxxxxxxx hidden xxxxxxxxxxxxxxxxx
E-mail address entered: xxxxxxxxxxxxxx hidden xxxxxxxxxxxxxxxxx
http validation is selected
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1640, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```

**Comment by aptalca** [comment]
Is this still an issue?
