### ISSUE TITLE
Add an option for force renewal

### ISSUE THREAD

**Issue by arnonh** [linuxserver/docker-letsencrypt#316]
Is it possible to add an option for force renewal?
in the script le-renew.sh for example 
Some times it is useful to force renew the certificates (when revoked for instance)
And using the existing scripts wold be better\easier then writing the whole certbot command for example "docker exec -it letsencrypt /app/le-renew.sh --force"  or something similar

**Comment by aptalca** [comment]
I don't see a valid reason for this. Why would the cert ever be revoked?

**Comment by TangentFoxy** [comment]
> Why would the cert ever be revoked?

Perhaps there was a security breach and it was manually revoked?

**Comment by aptalca** [comment]
Manually how? The container manages the certs and we don't provide or support ways to manually manage them inside the container.

**Comment by arnonh** [comment]
I have to say mine were actually revoked but I don't know why and they weren't automatically reissued so i needed to force renew.

**Comment by aptalca** [comment]
Do you mean expired? That's a whole another thing. If they expired, you just need to renew them, which is done by cron at 2:08am every night. Check the logs to see why previous cron attempts failed.

**Comment by CHBMB** [comment]
My take is that we can't change an image based on one report, where we're not really clear what's happened.

**Comment by arnonh** [comment]
It was revoked not expired, (That's why normal renew didn't help)
But if it only happened to me it really doesn't make sense to make any changes to the image.

**Comment by LBegnaud** [comment]
this does bring up an interesting point, though.

Wonder if the revoke should happen after a successful cert generation. I know that probably complicates the way things currently work (since revoke then deletes the files, and the cert generation happens if the file are missing), but it is a fear i have rebuilding containers with new domain lists. If something is wrong in dns for the new domains, i'd rather the container come up with the old cert than be stuck scrambling to solve the dns issues (and potentially hitting the max number of attempts and getting locked out with no cert)

**Comment by nemchik** [comment]
@LBegnaud in your scenario if I am reading it correctly you are mentioning a change in the domains, subdomains, or extra domains listed in your environment variables (and thus used to generate the cert). So assuming you have a setup like the following:
```
URL=yourdomain.url
SUBDOMAINS=www
EXTRA_DOMAINS=yourotherdomain.url
```
And before the current cert renews you change to
```
URL=yourdomain2.url
SUBDOMAINS=www
EXTRA_DOMAINS=yourotherdomain.url
```
And then you have issues due to incorrect DNS leading to a rate limit. At this point you can simply change back to the original variable values and renew the original cert without issue.

Or you can correct your DNS issues and then adjust your variables to add or remove a subdomain or an extra domain like so:
```
URL=yourdomain2.url
SUBDOMAINS=www,www2
EXTRA_DOMAINS=yourotherdomain.url
```
And you will be able to generate a cert.


The rate limit is applied to the exact combination of domains/subdomains/extra that you are requesting a cert for, so simply changing the combination will let you generate a cert (barring further DNS related issues).

On the topic of DNS issues there isn't really much that can be done by the letsencrypt container short of some kind of overly complicated attempt to pre-validate everything that is being requested (the combination mentioned above) and then only doing an actual request after confirming the pre-validation is successful. There is already an option in place, that will accomplish nearly the same thing, provided directly by LetsEncrypt (the service) and usable by this container by setting:
```
STAGING=true
```

Lastly, this is just a general statement addressed to anyone having issues with a cert generation; you can simply delete `/config/keys/` and restart the container and it will attempt to generate new certs (not renew, just new - this means the former cert will simply expire, but you'll have a new cert anyway). If an LSIO team member reviews this comment and disagrees please take note of their response and regard their recommendations above mine on this topic. I'll do my best to edit this response if a comment is left by an LSIO team member suggesting that this is incorrect or unsupported.

**Comment by LBegnaud** [comment]
all fair points of course.

In my particular scenario, i'm talking about changing the `SUBDOMAINS` parameter to add / remove proxied sites for a customer. I was under the impression that there were also limits for failed attempts on the WAN IP, but reading the [rate limits](https://letsencrypt.org/docs/rate-limits/) it seems I'm mistaken. So i really appreciate that clarification. Really eases my anxiety knowing that worst case i can add an extra subdomain, set `STAGING=true` and sort out my mess (which admittedly doesn't happen as much as it used to). 

We have over 100 containers running for our customers. Love this project. Thanks so much for the work.

**Comment by aptalca** [comment]
What you could also do is, whenever you want to make changes to the domains or subdomains, you can spin up a new container with the new domain (without touching the original one), subdomain passed as variables, set the staging to true, start it and see if it's able to get a cert. If so, you confirm that your dns settings are all correct and you are safe to recreate the original container with the new domains/subdomains.

Keep in mind that this works easily for the dns validation method, but http method requires port mapping and would be more complicated to have two letsencrypt containers on the same public IP without port clashing (still doable though).
