### ISSUE TITLE
/var/lib/libmaxminddb/GeoLite2-City.mmdb missing after update

### ISSUE THREAD

**Issue by Gerben-W** [linuxserver/docker-letsencrypt#344]
After the last 2 updates, I recieved the following error in logging:

`[emerg] MMDB_open("/var/lib/libmaxminddb/GeoLite2-City.mmdb") failed - Error opening the specified MaxMind DB file in /config/nginx/nginx.conf:36`

After manualy running ./etc/periodic/weekly/libmaxminddb from within the docker everything works again.

**Comment by aptalca** [comment]
It turns out, the database is only downloaded via the cron script and the file is saved inside the container. So when you update the image and recreate the container, there won't be a database file until the cron script runs again.

I'll PR a fix to make sure the db is downloaded during start if it doesn't exist.
