### ISSUE TITLE
request to add  php modules to letsencrypt

### ISSUE THREAD

**Issue by crgarrett79** [linuxserver/docker-letsencrypt#348]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

i want to request PHP XML-RPC module, Pear and PHP BCMath Extension if possible

**Comment by crgarrett79** [comment]
i want to request PHP XML-RPC module, Pear and PHP BCMath Extension if possible.

**Comment by CHBMB** [comment]
@aptalca is the maintainer of this container, so will leave it to him, I have checked the packages are actually available from the Alpine Linux repository and they are, because if they aren't available there then we definitely won't include them.

`php7-bcmath` [here](https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/php7-bcmath)
`php7-pear` [here](https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/php7-pear)
`php7-xmlrpc` [here](https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/php7-xmlrpc)

**Comment by crgarrett79** [comment]
yeah, @aptalca told me to request them here so they can be tracked.
