### ISSUE TITLE
Host not found

### ISSUE THREAD

**Issue by viruz82** [linuxserver/docker-letsencrypt#360]
Hello,

as I didn't got any help here: https://github.com/linuxserver/reverse-proxy-confs/issues/87 I try it here.

I have a lot of services running and a cname for all in my dns config (bind9). When I open the url in my browser nginx says:  `2019/09/03 08:03:06 [error] 368#368: *5 wordpress could not be resolved (3: Host not found)...`

nslookup lookes wired but can resolve the hostname:

> root@ebcdbc201640:/# nslookup wordpress
> nslookup: can't resolve '(null)': Name does not resolve
> 
> Name:      wordpress
> Address 1: 10.10.10.12 docker2.domain.com`

Ping looks good:

> root@ebcdbc201640:/# ping -c 3 wordpress
> PING wordpress (10.10.10.12): 56 data bytes
> 64 bytes from 10.10.10.12: seq=0 ttl=64 time=0.032 ms
> 64 bytes from 10.10.10.12: seq=1 ttl=64 time=0.056 ms
> 64 bytes from 10.10.10.12: seq=2 ttl=64 time=0.045 ms

And this is the resolv.conf of my container:

> search domain.com
> nameserver 127.0.0.11
> options ndots:1

Any ideas what I'm doing wrong? Wordpress is just an example and I know, that this isn't in your configs. I have this issue with all configs I use.

Cheers
Kai

**Comment by j0nnymoe** [comment]
Sounds like you haven't put both your wordpress and letsencrypt container on the same docker network. Going to close this as we reserve Github for bugs/issues rather than support. If you want to discuss further ideas then pop by our [Discord](https://discord.gg/YWrKVTn) or [Discourse](https://discourse.linuxserver.io/) forum.
