### ISSUE TITLE
add support for acme-dns as a DNS plugin

### ISSUE THREAD

**Issue by vincentjanv** [linuxserver/docker-letsencrypt#361]
I'm using this image right now with a single domain, but due to application requirements, I need to switch to a wildcard domain. 

I'm not authorised to change the nameservers/dns provider of the domain name, and they are not with any of the provided DNS plugins, That's why I've setup my own acme-dns instance from https://github.com/joohoi/acme-dns. Unfortunately, I cannot add a pre-auth hook nor is there a plugin. 

If there would be a custom plugin for acme-dns where we could add the username,password and domain of the acme-dns instance, that would be awesome. Another option would be the option to pass along a pre-auth hook (and share the script somehow). This way, people are not limited to using the DNS providers supported when using wildcards.

**Comment by aptalca** [comment]
We use the plugins that the official client, certbot, provides. There is no plugin for acme dns.

Adding a pre and post-hook option is possible, but honestly, it adds too much complexity. If a user is willing to go through all that trouble of setting up those hooks themselves, they might as well run certbot themselves.

**Comment by Germs2004** [comment]
@aptalca 
The command needed by [acme-dns](https://hub.docker.com/r/joohoi/acme-dns/) is this:
```
certbot certonly --manual --manual-auth-hook /path/to/acme-dns-auth.py --preferred-challenges dns --debug-challenges -d example.org -d \*.example.org
```

I understand you don't want to add a 3rd party plugin, but what if you just add an optional setting to the linuxserver/letsencrypt docker file called "custom parameters" so we can add the necessary parameters to make this work?  Or, if you prefer, you could add two optional settings: debug-challenges and manual-auth-hook.  Either solution should allow us to use our private dns server so handle the acme challenges.

I'd really like to use linuxserver's docker image instead of making my own that I'd have to support.  Like vincentjanv said, this would allow people to use letsencrypt with Google Domains and other unsupported dns servers and web server configurations.

Thank you
