### ISSUE TITLE
ImageMagick number of supported formats: 0

### ISSUE THREAD

**Issue by juliemars** [linuxserver/docker-letsencrypt#445]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The ImageMagick module is not working, in phpinfo I can see that it says "ImageMagick number of supported formats: 0" this is preventing some functions needing this library from working. 
If I disable the ImageMagick.ini file the system falls back to GD and works fine.
Nothing is logged in the docker or NGINX/php log for this error either.
I have deleted and recreated the container and image and tried on 2 different docker installs and issue remains on both. 

## Current Behavior
Images do not load generating a 500 error. 

![image](https://user-images.githubusercontent.com/17718528/81292988-760e4f00-9064-11ea-9e58-1920eb762d55.png)

## Steps to Reproduce

1. Setup new image
2. Use ImageMagick module (webtress uses this)
3. See 500 error/no image (webtress logs Cannot create thumbnail NoDecodeDelegateForThisImageFormat `PNG'"

## Environment
**OS:**  Tried on 2 Docker installs linux armv7l Raspbian GNU/Linux 10 (buster) and linux x86_64 (containerized)    
**CPU architecture:** armv7l and x86_64

**Comment by aptalca** [comment]
We can reproduce the issue, but have no idea why it's not working. Looks like an upstream issue (perhaps alpine).
We have this php module installed: https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/php7-pecl-imagick
It pulls in the imagemagick-libs: https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/imagemagick-libs
That's why php is listing the imagemagick library version. But no idea why it's not finding any supported formats.

Please report that upstream to alpine: https://gitlab.alpinelinux.org/groups/alpine/-/issues

In the meantime, installing imagemagick inside the container allows php to detect the formats: `apk add --no-cache imagemagick`
We will not add that to the image because then it will get too bloated (additional 70MB).
To make your changes persistent, you can see here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

When you open an issue with alpine, please drop a link here so we can track it as well.

Thanks

**Comment by juliemars** [comment]
Hi 

posted it to https://gitlab.alpinelinux.org/alpine/apk-tools/-/issues/10694

thanks

**Comment by aptalca** [comment]
there is now a docker mod for this: https://github.com/linuxserver/docker-mods/tree/letsencrypt-imagemagick
