### ISSUE TITLE
Use a port other than 443

### ISSUE THREAD

**Issue by dmelo** [linuxserver/docker-letsencrypt#76]
It seems that it is not possible to use a port other than the 443 to validate the domain. It would come in handy in situations where we already have port 443 bind to the Web container.

**Comment by aptalca** [comment]
This is "the" web container. If you have other webservers, you should reverse proxy them through this container so they can use the certs, because this container is designed to be the gatekeeper.

Also, you don't necessarily have to map port 443 on the host to this container. You just have to make sure that port 443 on the wan (router) ends up at port 443 inside the container. So it could go from 443 on wan to 444 on the host server, where docker is running, and then from 444 on the host to 443 inside the container (through the docker run/create command). The 443 on the wan is a restriction of letsencrypt. They only validate through 80 or 443.

**Comment by dmelo** [comment]
Thank you for clarifying. I was able to get it working.
