### ISSUE TITLE
Suggestion: Configuration to hit staging

### ISSUE THREAD

**Issue by collinsauve** [linuxserver/docker-letsencrypt#82]
I've been mucking around with trying to get a letsencrypt reverse proxy going for a number of domains, and I've hit the "too many registrations for this IP" error.

Can I suggest an option to allow hitting the [staging environment](https://letsencrypt.org/docs/staging-environment/)?   Something like `-e STAGING=true` that would make all calls to `certbot` include `--staging`.

**Comment by aptalca** [comment]
I'll give it some thought. 

It wouldn't be as simple as adding the `--staging` tag as there would have to be other considerations and algorithms regarding switching back and forth between staging and production. It might be more trouble than it's worth.

Usually when you hit the limit, you can either add or remove a subdomain, or wait an hour and you should be fine.

**Comment by bablat** [comment]
+1, I'm also hitting this issue while working on my configuration.
Perhaps a tag, like the nzbget container? something like linuxserver/letsencrypt:staging would work great!

**Comment by aptalca** [comment]
We realized the majority of users running into the throttling issue is because they create the container with `restart=always`. When the validation fails, the container is stopped, but with restart=always, it starts right back up and tries again. It will keep doing that until it is throttled.

#91 fixes that problem by halting the container instead of a stop. So if you make a mistake with the variables, you'll get a message in the log.

We don't have plans for adding a staging flag/tag at this time.

**Comment by collinsauve** [comment]
> We realized the majority of users running into the throttling issue is because they create the container with restart=always.

Yup, that's me too!  Thanks.
